//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string adress { get; set; }
        public Nullable<double> weight { get; set; }
        public string coment { get; set; }
        public string type { get; set; }
        public Nullable<double> cost_value { get; set; }
    }
}
